I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 2, in script
    python:
  File "game/script.rpy", line 2, in script
    python:
  File "game/script.rpy", line 4, in <module>
    import gspread
ImportError: No module named google.oauth2.credentials

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-7.4.11-sdk/renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-7.4.11-sdk/renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 2, in script
    python:
  File "game/script.rpy", line 2, in script
    python:
  File "/Applications/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 4, in <module>
    import gspread
  File "/Applications/renpy-7.4.11-sdk/lib/python2.7/gspread/__init__.py", line 16, in <module>
    from .auth import oauth, oauth_from_dict, service_account, service_account_from_dict
  File "/Applications/renpy-7.4.11-sdk/lib/python2.7/gspread/auth.py", line 12, in <module>
    from google.oauth2.credentials import Credentials
ImportError: No module named google.oauth2.credentials

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
IDP2022 1.0
Sat May 28 16:26:25 2022
